// NCS 歌曲数据（来源：ncs.io 公开信息）
// 每首歌曲：id, title, artist, genre, year
const NCS_SONGS = [
  {id:"s001",title:"Fade",artist:"Alan Walker",genre:"EDM",year:2014,popular:100},
  {id:"s002",title:"On & On (feat. Daniel Levi)",artist:"Cartoon, Daniel Levi, Jéja",genre:"Drum & Bass",year:2015,popular:99},
  {id:"s003",title:"Spectre",artist:"Alan Walker",genre:"EDM",year:2015,popular:98},
  {id:"s004",title:"Invincible",artist:"DEAF KEV",genre:"Glitch Hop",year:2015,popular:97},
  {id:"s005",title:"Sky High",artist:"Elektronomia",genre:"Electro",year:2015,popular:96},
  {id:"s006",title:"Symbolism",artist:"Electro-Light",genre:"Electro",year:2015,popular:95},
  {id:"s007",title:"Why We Lose (feat. Coleman Trapp)",artist:"Cartoon, Coleman Trapp",genre:"Electronic",year:2015,popular:94},
  {id:"s008",title:"Mortals (feat. Laura Brehm)",artist:"Warriyo, Laura Brehm",genre:"Trap",year:2015,popular:93},
  {id:"s009",title:"Hope",artist:"Tobu",genre:"House",year:2014,popular:92},
  {id:"s010",title:"Shine",artist:"Spektrem",genre:"Progressive House",year:2014,popular:91},
  {id:"s011",title:"Force",artist:"Alan Walker",genre:"EDM",year:2015,popular:90},
  {id:"s012",title:"Cradles",artist:"Sub Urban",genre:"Alternative",year:2019,popular:89},
  {id:"s013",title:"Fearless Pt. II (feat. Chris Linton)",artist:"Lost Sky, Chris Linton",genre:"Trap",year:2017,popular:88},
  {id:"s014",title:"Invisible",artist:"Julius Dreisig, Zeus X Crona",genre:"Trap",year:2019,popular:87},
  {id:"s015",title:"Feel Good",artist:"Syn Cole",genre:"House",year:2014,popular:86},
  {id:"s016",title:"Superhero (feat. Chris Linton)",artist:"Unknown Brain, Chris Linton",genre:"Trap",year:2016,popular:85},
  {id:"s017",title:"We Are",artist:"Jo Cohen, Sex Whales",genre:"Trap",year:2016,popular:84},
  {id:"s018",title:"Sunburst",artist:"Tobu, Itro",genre:"House",year:2014,popular:83},
  {id:"s019",title:"Ark",artist:"Ship Wrek, Zookeepers",genre:"Trap",year:2016,popular:82},
  {id:"s020",title:"Hellcat",artist:"Desmeon",genre:"Trap",year:2016,popular:81},
  {id:"s021",title:"Light It Up (feat. Jex)",artist:"Robin Hustin, TobiMorrow, Jex",genre:"EDM",year:2016,popular:80},
  {id:"s022",title:"Candyland",artist:"Tobu",genre:"House",year:2015,popular:79},
  {id:"s023",title:"Firefly",artist:"Jim Yosef",genre:"Progressive House",year:2016,popular:78},
  {id:"s024",title:"Energy",artist:"Elektronomia",genre:"House",year:2016,popular:77},
  {id:"s025",title:"Dreams Pt. II (feat. Sara Skinner)",artist:"Lost Sky, Sara Skinner",genre:"Melodic Dubstep",year:2018,popular:76},
  {id:"s026",title:"Make Me Move (feat. Karra)",artist:"Culture Code, Karra",genre:"Trap",year:2016,popular:75},
  {id:"s027",title:"Turn It Up",artist:"Anikdote",genre:"Trap",year:2016,popular:74},
  {id:"s028",title:"MATAFAKA (feat. Marvin Divine)",artist:"Unknown Brain, Marvin Divine",genre:"Trap",year:2017,popular:73},
  {id:"s029",title:"High",artist:"JPB",genre:"Future House",year:2016,popular:72},
  {id:"s030",title:"Link",artist:"Jim Yosef",genre:"Progressive House",year:2016,popular:71},
  {id:"s031",title:"Let's Go!",artist:"Lensko",genre:"Electro",year:2015,popular:70},
  {id:"s032",title:"Adventure",artist:"JJD",genre:"Indie",year:2016,popular:69},
  {id:"s033",title:"Why Do I? (feat. Bri Tolani)",artist:"Unknown Brain, Bri Tolani",genre:"Trap",year:2017,popular:68},
  {id:"s034",title:"Limitless",artist:"Elektronomia",genre:"Electro",year:2017,popular:67},
  {id:"s035",title:"Forever (feat. Brenton Mattheus)",artist:"Vanze, Brenton Mattheus",genre:"Future House",year:2016,popular:66},
  {id:"s036",title:"C U Again (feat. Mikk Mäe)",artist:"Cartoon, Futuristik, Mikk Mäe",genre:"Electronic",year:2016,popular:65},
  {id:"s037",title:"Life",artist:"Tobu",genre:"House",year:2015,popular:64},
  {id:"s038",title:"Everything",artist:"Diamond Eyes",genre:"Dubstep",year:2017,popular:63},
  {id:"s039",title:"Tropic Love",artist:"Diviners, Contacreast",genre:"House",year:2015,popular:62},
  {id:"s040",title:"Fall To Light",artist:"Laszlo",genre:"Progressive House",year:2015,popular:61},
  {id:"s041",title:"Pill (feat. Emma Sameth)",artist:"Heuse, Zeus X Crona, Emma Sameth",genre:"Trap",year:2018,popular:60},
  {id:"s042",title:"Puzzle",artist:"RetroVision",genre:"House",year:2017,popular:59},
  {id:"s043",title:"Earth",artist:"K-391",genre:"House",year:2016,popular:58},
  {id:"s044",title:"Love U",artist:"Razihel",genre:"Dubstep",year:2015,popular:57},
  {id:"s045",title:"Stronger",artist:"Prismo",genre:"Dubstep",year:2015,popular:56},
  {id:"s046",title:"Where We Started (feat. Jex)",artist:"Lost Sky, Jex",genre:"Melodic Dubstep",year:2018,popular:55},
  {id:"s047",title:"Defeat The Night (feat. Ashley Apollodor)",artist:"JPB, Ashley Apollodor",genre:"Trap",year:2016,popular:54},
  {id:"s048",title:"You",artist:"Axol, Alex Skrindo",genre:"House",year:2016,popular:53},
  {id:"s049",title:"H.A.Y",artist:"Clarx",genre:"Trap",year:2017,popular:52},
  {id:"s050",title:"Fearless",artist:"Lost Sky",genre:"Melodic Dubstep",year:2017,popular:51},
  {id:"s051",title:"Nekozilla",artist:"Different Heaven",genre:"Hardstyle",year:2016,popular:50},
  {id:"s052",title:"Royalty",artist:"Egzod, Maestro Chives, Neoni",genre:"Trap",year:2020,popular:49},
  {id:"s053",title:"Shootin Stars",artist:"Aero Chord, DDark",genre:"Trap",year:2017,popular:48},
  {id:"s054",title:"Control",artist:"Unknown Brain, Jex, Rival",genre:"Trap",year:2018,popular:47},
  {id:"s055",title:"Savannah (feat. Philly K)",artist:"Diviners, Philly K",genre:"Indie",year:2018,popular:46},
  {id:"s056",title:"Cloud 9",artist:"Itro, Tobu",genre:"House",year:2014,popular:45},
  {id:"s057",title:"Infectious",artist:"Tobu",genre:"House",year:2014,popular:44},
  {id:"s058",title:"My Heart",artist:"EH!DE, Different Heaven",genre:"Dubstep",year:2014,popular:43},
  {id:"s059",title:"So Funky",artist:"NIVIRO",genre:"House",year:2018,popular:42},
  {id:"s060",title:"Perfect 10 (feat. Heather Sommer)",artist:"Unknown Brain, Heather Sommer",genre:"Trap",year:2018,popular:41},
  {id:"s061",title:"Biscuit",artist:"Raven & Kreyn",genre:"House",year:2018,popular:40},
  {id:"s062",title:"With You",artist:"Marin Hoxha",genre:"Chill",year:2018,popular:39},
  {id:"s063",title:"Ber Zer Ker",artist:"WATEVA",genre:"Bass",year:2018,popular:38},
  {id:"s064",title:"Cake",artist:"RetroVision",genre:"House",year:2018,popular:37},
  {id:"s065",title:"Venus (feat. Mylk)",artist:"Michael White, MYLK",genre:"House",year:2018,popular:36},
  {id:"s066",title:"Summersong 2018",artist:"Elektronomia",genre:"House",year:2018,popular:35},
  {id:"s067",title:"Dreamers",artist:"Glude",genre:"Trap",year:2018,popular:34},
  {id:"s068",title:"The Apocalypse",artist:"NIVIRO",genre:"Hardstyle",year:2018,popular:33},
  {id:"s069",title:"Ghost (feat. Eli Raain)",artist:"Cadmium, Eli Raain",genre:"Chill",year:2018,popular:32},
  {id:"s070",title:"Donuts",artist:"2SCOOPS",genre:"EDM",year:2018,popular:31},
  {id:"s071",title:"Universe",artist:"Egzod, Tanjent",genre:"Trap",year:2018,popular:30},
  {id:"s072",title:"Dino",artist:"Mountkid",genre:"Trap",year:2018,popular:29},
  {id:"s073",title:"Ignoring My Heart",artist:"T-Mass",genre:"Trap",year:2018,popular:28},
  {id:"s074",title:"The Light",artist:"Phantom Sage",genre:"Drum & Bass",year:2017,popular:27},
  {id:"s075",title:"Away (feat. Byndy)",artist:"Phantom Sage, Byndy",genre:"Dubstep",year:2017,popular:26},
  {id:"s076",title:"Everlasting",artist:"Jim Yosef, Ephixa",genre:"EDM",year:2017,popular:25},
  {id:"s077",title:"Vertigo",artist:"Rob Gasser, Laura Brehm",genre:"Drumstep",year:2017,popular:24},
  {id:"s078",title:"Savage",artist:"Paul Flint",genre:"Dubstep",year:2017,popular:23},
  {id:"s079",title:"Feel Like Horrible",artist:"Different Heaven, Sian Area",genre:"Drum & Bass",year:2017,popular:22},
  {id:"s080",title:"Beside You (feat. Soundr)",artist:"Rameses B, Soundr",genre:"Drum & Bass",year:2017,popular:21},
  {id:"s081",title:"Start That Fire",artist:"ÉWN, Whogaux",genre:"Trap",year:2017,popular:20},
  {id:"s082",title:"Polaris",artist:"Blazars",genre:"EDM",year:2017,popular:19},
  {id:"s083",title:"Whole",artist:"Chime, Adam Tell",genre:"Dubstep",year:2017,popular:18},
  {id:"s084",title:"Wait For You (feat. Anna Yvette)",artist:"Electro-Light, Jordan Kelvin James, Anna Yvette",genre:"Drum & Bass",year:2017,popular:17},
  {id:"s085",title:"Heroes",artist:"RetroVision",genre:"House",year:2017,popular:16},
  {id:"s086",title:"Feels",artist:"ÉWN",genre:"Trap",year:2017,popular:15},
  {id:"s087",title:"Pain (feat. Mia Vaile)",artist:"Ship Wrek, Mia Vaile",genre:"Trap",year:2017,popular:14},
  {id:"s088",title:"Donuts",artist:"Jensation",genre:"House",year:2017,popular:13},
  {id:"s089",title:"Remember (feat. The Tech Thieves)",artist:"Axol, Levianth, The Tech Thieves",genre:"Trap",year:2017,popular:12},
  {id:"s090",title:"Blueshift",artist:"Catas, Kasger",genre:"Drum & Bass",year:2017,popular:11},
  {id:"s091",title:"The Wizard",artist:"SKYLINK",genre:"Melodic Dubstep",year:2017,popular:10},
  {id:"s092",title:"Escape With Me (feat. Charlotte Haining)",artist:"Charlotte Haining, Halcyon",genre:"Melodic Dubstep",year:2016,popular:9},
  {id:"s093",title:"A New Light",artist:"Valcos",genre:"EDM",year:2016,popular:8},
  {id:"s094",title:"Imma Killa!",artist:"Anikdote",genre:"Trap",year:2016,popular:7},
  {id:"s095",title:"Migraine (feat. Anna Yvette)",artist:"Ellis, Anna Yvette",genre:"Future House",year:2016,popular:6},
  {id:"s096",title:"ILY",artist:"Axol",genre:"EDM",year:2016,popular:5},
  {id:"s097",title:"Canary",artist:"Jim Yosef",genre:"Future House",year:2016,popular:4},
  {id:"s098",title:"Still Need You (feat. AWR)",artist:"Uplink, AWR",genre:"House",year:2016,popular:3},
  {id:"s099",title:"Masked Raver",artist:"Vexento",genre:"House",year:2016,popular:2},
  {id:"s100",title:"Melrose At Midnight",artist:"Light Years Away",genre:"Melodic Dubstep",year:2016,popular:1},
  {id:"s101",title:"Happy Accidents",artist:"Inukshuk",genre:"Hardstyle",year:2015,popular:0},
  {id:"s102",title:"Let Me See You",artist:"Naima",genre:"Trap",year:2015,popular:0},
  {id:"s103",title:"Levitate",artist:"JPB",genre:"Future House",year:2015,popular:0},
  {id:"s104",title:"Change Your Ways (feat. Charlotte Haining)",artist:"High Maintenance, Charlotte Haining",genre:"Trap",year:2015,popular:0},
  {id:"s105",title:"Losing Sleep (feat. Tara Louise)",artist:"Disfigure, Tara Louise",genre:"Chill",year:2017,popular:0},
  {id:"s106",title:"Heaven",artist:"RIVERO, Anna Yvette",genre:"Trap",year:2018,popular:0},
  {id:"s107",title:"Somebody",artist:"Sekai",genre:"Melodic Dubstep",year:2018,popular:0},
  {id:"s108",title:"Paper Crowns (feat. Leo The Kind)",artist:"Egzod, Leo The Kind",genre:"Electronic",year:2018,popular:0},
  {id:"s109",title:"In The Air",artist:"Raven & Kreyn",genre:"House",year:2018,popular:0},
  {id:"s110",title:"Together",artist:"3rd Prototype",genre:"Electronic",year:2017,popular:0},
  {id:"s111",title:"Light Up The Sky (feat. Soundr)",artist:"Axtasia, Soundr",genre:"Dubstep",year:2017,popular:0},
  {id:"s112",title:"Heroes Tonight (feat. Johnning)",artist:"Janji, Johnning",genre:"EDM",year:2015,popular:50},
  {id:"s113",title:"Blank",artist:"Disfigure",genre:"Melodic Dubstep",year:2015,popular:51},
  {id:"s114",title:"Roots",artist:"Tobu",genre:"House",year:2014,popular:0},
  {id:"s115",title:"Hope (Original Mix)",artist:"Tobu",genre:"House",year:2014,popular:52},
];
